### PR TITLE
Improve wildcards and fix a bug

### PR DESCRIPTION
**Pull request by kamnxt**
This commit fixes two issues with wildcards:

- Using a single count value no longer worked due to .strip() being called on a None value from matching the upper range, when using a wildcard like {2$$a|b|c}, while {2-2$$a|b|c} worked fine. Added a check to fix that.

- Choosing options was implemented in an odd way. The code would choose up to `count` values, then put them in a `set` to prevent duplicates. Then retry up to 10 times to get values in case the correct count wasn't reached. This had a few issues: {2$$a|a|b} would always choose "b a", always in this order! However, {2$$1::a|a|b}, which should be identical, gives either "a a" or "b a"!

- When the number of items to choose was more than the count of items to choose, the items would be returned in the original order, meaning for example {3-6$$a|b|c|d} returns "a b c d" way more often than it should. This is changed to shuffle the order when choosing all the items.

- As NumPy already had a way to choose N items without replacement and with weights, the code has been changed to use a NumPy Generator. This means previous seeds are no longer compatible, but also means we don't re-seed the built-in Python `random` generator.

- I have also added a "ImpactWildcardUnprocessed" node, in order to have a multiline text input node that doesn't do ComfyUI's built in wildcard replacement, so it's possible to put a prompt in a separate node from the WildcardProcessor (or have a few ones to connect manually). Due to the way things are processed both on the JS side and the backend side, sadly concatenating text for use in wildcards doesn't work yet.

### CODE REVIEW

**Comment by kamnxt** [comment]
Just noticed the first bug was fixed two days ago, oops. Feel free to choose either my or the already implemented fix for that. Other bugs still remain in the `main` branch though.

**Comment by ltdrdata** [comment]
"ImpactWildcardUnprocessed" is simply used to avoid built-in dynamic prompts, right?

**Comment by kamnxt** [comment]
That's right, it's simply a multiline input with built-in dynamic prompts disabled.

**Comment by ltdrdata** [comment]
> That's right, it's simply a multiline input with built-in dynamic prompts disabled.
> […](#)
> On November 26, 2023 1:16:48 AM GMT+01:00, "Dr.Lt.Data" ***@***.***> wrote: "ImpactWildcardUnprocessed" is simply used to avoid built-in dynamic prompts, right? -- Reply to this email directly or view it on GitHub: [#319 (comment)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/319#issuecomment-1826449748) You are receiving this because you authored the thread. Message ID: ***@***.***>

In such cases, you can switch to fixed mode in ImpactWildcardProcessor and directly modify the `populated prompt` as needed.

**Comment by kamnxt** [comment]
Huh, that actually works, neat. Should I remove the node from my PR?
image

**Review by ltdrdata — APPROVED** [review]
Unprocessed node is removed.
And minor bugfix, about shuffle function, is applied

**Pull request merged**
